export const accordionItems = [
  {
    name: 'Slide flip',
    img: '/posts/20240109-perspective/slide.gif',
    see: '/practice/slideFlip',
    source: 'https://3dtransforms.desandro.com/',
    description: '/blog/20240109-perspective',
  },
  {
    name: 'Card flip',
    img: '/posts/20240109-perspective/flip.gif',
    see: '/practice/cardFlip',
    source: 'https://3dtransforms.desandro.com/',
    description: '/blog/20240109-perspective',
  },
  {
    name: '3D tilting card',
    img: '/posts/20240208-3DCard/card.gif',
    see: '/practice/3DCard',
    source: 'https://www.youtube.com/watch?v=Z-3tPXf9a7M&list=WL&index=1&t=27s',
    description: '',
  },
  {
    name: 'Tucked Corenr photo',
    img: '/posts/20240221-tucked/tucked.png',
    see: '/practice/TuckedCornerPhoto',
    source: 'https://www.youtube.com/watch?v=3T-RETzcqpU&t=700s',
    description: '',
  },
  {
    name: 'Star rating',
    img: '/posts/20240221-star-rating/rating.gif',
    see: '/practice/starRating',
    source: 'https://www.youtube.com/watch?v=oiai47goI6A',
    description: '',
  },
  {
    name: 'Aura box',
    img: '/posts/20240221-aura/aura.gif',
    see: '/practice/auraBox',
    source: 'https://www.youtube.com/watch?v=VqSz7myU5iE&t=65s',
    description: '',
  },
  {
    name: 'Text with shadow',
    img: '/posts/20240222-effects/text-shadow.png',
    see: '/practice/textWithShadow',
    source: 'https://www.youtube.com/watch?v=pbD55DJgOlw&t=806s',
    description: '',
  },
  {
    name: 'Fancy link',
    img: '/posts/20240222-effects/link.gif',
    see: '/practice/fancyLink',
    source: 'https://www.youtube.com/watch?v=pbD55DJgOlw&t=806s',
    description: '',
  },
];
